<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html lang='en'>
<head>
    <title>openGuildHall Install</title>
    <?=$this->stylesheets()?>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js"></script>
    <?=$this->javascripts()?>
    
</head>
<body>
	<div class="content">
		<h1>openGuildHall Installation</h1>
		<hr />
		<?=$this->content?>
		<hr />
		<?=VERSION?><br />
		Copyright &copy; 2011 Ryan Capote
	</div>
</body>
</html>