<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html lang='en'>
<head>
    <title>openGuildHall :: <?=$this->pagetitle?></title>
    <link rel='stylesheet' href='<?=SITE_PATH?>Application/Views/user_bar.css' type='text/css' />
    <link rel='stylesheet' href='<?=SITE_PATH?>Application/Views/sprites.css' type='text/css' />
    <?=$this->stylesheets()?>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js"></script>
    <?=$this->javascripts()?>
    
    <script type="text/javascript">
		function checkBrowserVersion() {
			if(navigator.appVersion.indexOf("MSIE 6.")==1 || navigator.appVersion.indexOf("MSIE 7.")==1) {
				$("#browsererror").slideDown();
			}
		}
		
	</script>    
</head>
<body onload="javascript:checkBrowserVersion();">
	<div id="browsererror" style="display: none;">
		We're sorry, but the browser you are currently using is not supported. Please upgrade to a modern browser such as <a href="http://google.com/chrome">Chrome</a> or <a href="http://firefox.com">Firefox</a>.
	</div>
    
    <div id="bodywrapper">
        <div id="nav">
    	<ol>
            <li><a href="<?=SITE_PATH?>">Home</a></li>
            <li><a href="<?=SITE_PATH?>page/information">Information</a></li>
            <li><a href="<?=SITE_PATH?>roster">Roster</a></li>
            <li><a href="<?=SITE_PATH?>forum">Forum</a></li>
       </ol>
       </div>
    <div id="header">
        	<div id="usernav">
        		<? if(isLoggedIn()) : ?>
	        		Welcome, <?=getUsername()?>
	        		<ol>
	        			<!--<li><?=alink('#', 'Notifications')?></li>-->
	        			<li><?=alink('user/controls', 'User Settings')?></li>
	        			
	        			<? if(Acl::getInstance()->hasAccess('Admin', 'Controls', 'Edit') == ALLOW) : ?>
	        				<li><?=alink('admin', 'Admin Controls')?></li>
	        			<? endif; ?>
	        			
	        			<li><?=alink('user/profile/'.getUsername(), 'Profile')?>
	        			<li><?=alink('user/logout', 'Log out')?></li>
	        		</ol>
	        		<? else : ?>
	        		Welcome, Guest
	        		<ol>
	        			<li><?=alink('user/login', 'Login')?></li>
	        			<li><?=alink('user/register', 'Register')?></li>
	        		</ol>
        		<? endif; ?>
        	</div>
           
    </div>
    <div id="content">
        <h2 id="pagetitle"><?=$this->pagetitle?></h2>
 
        <?=$this->content?>
	   <div style="clear:both;">&nbsp;</div>
			<div id="footer">
				<div id="credit">
	                <a href="https://github.com/rcapote/openGuildHall"><?=VERSION?></a><br />
	                <?=getQueryCount()?> queries were performed on this page.
				</div>
			</div>
    </div>
    </div>
</body>
</html>