
<div class="container">
	<div class="header">
		User Controls
	</div>
	<ol class="admin">
		<li><?=alink('admin/edituser', 'Edit User')?></li>
		<li><?=alink('admin/usergroups', 'User Groups')?></li>
		<li><?=alink('admin/groupacl', 'Group Permissions')?></li>
	</ol>
	
	<div class="header">
		Forum Controls
	</div>
	<ol class="admin">
		<li><?=alink('admin/forumcategories', 'Categories')?></li>
		<li><?=alink('admin/forumboards', 'Boards')?></li>
	</ol>
</div>