<h2 class="h">History</h2>
<p>Redeemed has gone through a number of web site changes in it's history. From the old 
gray/black/blue layout that we had back in 2000, we went to a new red and black layout
designed and coded by Drachemorder. That site featured a file uplaoder, multiplayer chess, and
a few other features. Sometime in 2008, the site was hacked and a lot of the information in 
the database was corrupted or just deleted altogether. This caused a majority of the site to stop
working.</p>

<p>Knowing that writing the whole website would be a great learning experience, I stepped up to the
massive project of writing a whole content management system and forum system from scratch. The
project turned into a lot more work than I first anticipated, expecially as someone with minimal experience
writing such software.</p>

<p>I first began trying different layouts and color schemes back in Janurary of 2009. Since then, the new 
site has gone through enough rewrites to satisfy any developer for their lifetime. If I can remember correctly, 
over the past year and a half, the site has been rewritten a total of 4 times. There was the first PHP4 version, 
which was outdated when Drache upadated the host to PHP5. I then wrote the whole site using Zend framework. 
When we uploaded that version to the test server, it completely failed. That code was a complete and utter 
disaster and would have been aweful to try and fix. After that major discouragement, I set out to rewrite the 
set using only my code so that I would know how to fix any problems that would arise. After many months, I finished 
that version of the site and we uploaded it to the test server. However, after those 3 rewrites, and a working beta
I STILL was not happy with the code.</p>

<p>From version 3 of the site, I pulled the core mechanics and changed some fundamental workings of it to 
produce a custom framework. Impressed with out well the framework turned out, I decided to move
Redeemed to use the framework. And that is where the site stands now. Finally, after 4 rewrites, the code
is in a state that I believe will be maintainable well into the future, as long as PHP and MySQL don't go
out of date.</p>

<h2 class="h">Donations</h2>
<p>I have been working on the Redeemed site in my spare time for the past almsot 2 years on a volunteer basis.
I would greatly appreciate a donation as an apprieciation for my work on the site. I would greatly apprecieate
a cash donation through PayPal or something from my Amazon wishlist.</p>

<h2 class="h">Change log</h2>

<h3 class="version">V2.0.0 (Aug 19th 2010)</h3>
<ol class="changelog">
	<li>Moved site to new framework</li>
	<li>Increased password security</li>
	<li>Added theme selection and 'DarkBlue' theme</li>
</ol>
<br /><br />
<span>
- Cirdan<br />
<a href="http://www.twitter.com/rcapote">Twitter</a> &middot;
<a href="http://www.facebook.com/rcapote">Facebook</a>

</span>
