<html><head>
<title>Redeemed :: Chat</title>
<style type="text/css">
		body{background-color: #000;}
</style>
</head><body>

<p>
<b>Server:</b> redeemed.servegame.com 
<b>Port:</b> 11111 
<b>Channel:</b> #redeemed
</p>
<applet code=IRCApplet.class codebase='<?=SITE_PATH?>pjirc/'
	archive="irc.jar,pixx.jar" width="640" height="400">
	
	<param name="CABINETS" value="pjirc/irc.cab,pjirc/securedirc.cab,pjirc/pixx.cab" />

    <? if(isLoggedIn()) : ?>
    <param name="nick" value="<?=$this->getUsername()?>" />
    <param name="nick" value="<?=$this->getUsername()?>2" />
    <? else: ?>
	<param name="nick" value="AnonymousCoward" />
	<param name="alternatenick" value="AnonymousCoward2" />
	<? endif; ?>
	
	<param name="name" value="Web Chat User" />
	<param name="host" value="redeemed.servegame.com" />
	<param name="port" value="11111" />
	<param name="gui" value="pixx" />
	<param name="quitmessage" value="DELETED!!11" />
	<param name="asl" value="true" />
	<param name="command1" value="join #redeemed" />
	<param name="style:bitmapsmileys" value="true" />
	<param name="style:smiley1" value=":) img/sourire.gif" />
	<param name="style:smiley2" value=":-) img/sourire.gif" />
	<param name="style:smiley3" value=":-D img/content.gif" />
	<param name="style:smiley4" value=":d img/content.gif" />
	<param name="style:smiley5" value=":-O img/OH-2.gif" />
	<param name="style:smiley6" value=":o img/OH-1.gif" />
	<param name="style:smiley7" value=":-P img/langue.gif" />
	<param name="style:smiley8" value=":p img/langue.gif" />
	<param name="style:smiley9" value=";-) img/clin-oeuil.gif" />
	<param name="style:smiley10" value=";) img/clin-oeuil.gif" />
	<param name="style:smiley11" value=":-( img/triste.gif" />
	<param name="style:smiley12" value=":( img/triste.gif" />
	<param name="style:smiley13" value=":-| img/OH-3.gif" />
	<param name="style:smiley14" value=":| img/OH-3.gif" />
	<param name="style:smiley15" value=":'( img/pleure.gif" />
	<param name="style:smiley16" value=":$ img/rouge.gif" />
	<param name="style:smiley17" value=":-$ img/rouge.gif" />
	<param name="style:smiley18" value="(H) img/cool.gif" />
	<param name="style:smiley19" value="(h) img/cool.gif" />
	<param name="style:smiley20" value=":-@ img/enerve1.gif" />
	<param name="style:smiley21" value=":@ img/enerve2.gif" />
	<param name="style:smiley22" value=":-S img/roll-eyes.gif" />
	<param name="style:smiley23" value=":s img/roll-eyes.gif" />
	<param name="style:floatingasl" value="true" />


	<param name="pixx:highlight" value="true" />
	<param name="pixx:highlightnick" value="true" />

</applet>

</body></html>